### ISSUE TITLE
i2c master/slave connections

### ISSUE THREAD

**Issue by noscene** [noscene/doppler4arduino#6]
need to fix in samd51 libs ?

some links:
https://forums.adafruit.com/viewtopic.php?f=63&t=135452
https://forum.arduino.cc/index.php?topic=526168.30
https://github.com/arduino/ArduinoCore-samd/issues/322

**Comment by noscene** [comment]
this work in sketch but looks like the first Wire.write cant not be read
```
void SERCOM2_0_Handler()    {   Wire.onService();         }
void SERCOM2_1_Handler()    {   Wire.onService();         }
void SERCOM2_2_Handler()    {   Wire.onService();         }
void SERCOM2_3_Handler()    {   Wire.onService();         }
```

**Comment by noscene** [comment]
was fixed by adafruit
https://github.com/adafruit/ArduinoCore-samd/issues/45

**Comment by MichelReij** [comment]
Is this really fixed? I am having problems getting an Adafruit ItsyBitsy M4 getting to run the standard Arduino Wire_Master_Writer sketch to run. It freezes up as soon as it attempts to start the i2c communication.
